travis:
  secure:
    BINSTAR_TOKEN: nQtqGHEPw6mNq6NYqqcp3SBMdf3yVzKnFFGhNeB5B2OMzvhoEKVVqzj5tjqqI3kvdiS5XFEimfQ1fweBSRv96Xx1QMCi0vPPj7QezVoSJEtiEe5uOKcqs3h/xlMcyGx22+k/gLtlXgLBekQ7F3n5RsAcMV9GuXZ0lcPhz8FXDLJS8YDT3Ys/YzwBBQR0/bjR2ONHuTBUL+TOd9iGdKXnCA+9wXMEKWA4j50YRxDWvefK9silxlPV6lrTnNn6GXf73LxPGS6T9ObvknY0uc3McXdg3Jsu+bZaBBFmA9AsbqfSYORLWWMZP1QiQAnTweW/CEyX867vn6gtC2yzYojGYSVuvNnnfp86jxUgUeaoAafsC8MI/P8dJqgWvDLdk+w8COhHbzvLXmbGfrXfw+0jTT15dmIJyejiSlyvsIET1ksZbatdhdsjIhpsDXFdDKymq3cjT0gDNUGe9Dz8ic0PJCJ0D6xEmeBYRPWEbpog9NR8Zl2RykpP8ZAnyT6+615dP7kSUKKVPUQtEIO8E9vy4jTML6Z3rXjUJIfbpb6TUfBaH+l18j6NuVXlyEEvUnj41Kds1ttW8m2+YES8L+XWlI6eyUKQ7oRH/hZ73nbugj+ot1wjSQwj2hgxE4tc6OtQRSaXjumtSyHMgF6dLrwgszAb8WLVINT21z6WKIzOFiQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
