appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: o5sL8fJPUvVCAbEtJboL9BNHIjxIurOLTz9p2HPtUgEpsPmD4FuRsL5b55OxHKyuH6WxMHh2GmV1LFh6YpQFVDQ+jopiB/YTIMuns8ViEot3r1p+LG/ACZ3/Aebi6lpDMwT1/czoFpebSVRcFO3rCyzNrf/kXJY0iD+/EcoFyUJgedUNTglEDkK+3gDrc9pzNguUo3AwkQI9uy4VhW5Q9V6zOR577Dep+FebnLUGF44holwgnf2Zc7RBulZf9O5R5aw5XdAMg029Cmx+//FVemxJgSGsIAjTHxkUsShaQgQVwU4xk/Ou/VYOYPfFM7GHqZD9NsiW0c9Unp+vKbPLKD0XIBaVNCh8+L00rdS/wP5T6s5mcnVqJl4fRn+O3tf4VWHeYDrcv28cXijWV5g9ZcV6O5cAVvNhQ4t6tGIArLE82+4LT3eC2xcRU8LQuJs4/ss55NNnqMijmk3w+v8hKhy4H/hTqcivQvgXqNkZpary41TeMt79ptJO1F814gf2zZzTWHigv9JN0+xnRwCd86slLra92RC7rkjuF9MGnkPDpk8zk5yHx/W+dnOh6RhEt0CrVq0/mRWinqOF+DXD4NAOH+vZF92fZmq80IyfHUdbpOrF/3W4+2iB1vyl03I2uPRkvUmPwQdRiWrMYBLgtKhle/qJNXC7orldcKjVvxo=}
